# -*- coding: utf-8 -*-
"""Exploring_ML_Models_for_Regression_and_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9uq_4XXVTDHvQrX08aMO9Bj2Muvis2n

# Exploring ML Models for Regression and Classification

## Task 1. Regression
"""

!pip install optuna

# Import necessary libraries
import pandas as pd
import numpy as np
import scipy
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as skl
import joblib
import optuna
import tensorflow as tf

# Scikit-learn modules
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    explained_variance_score,
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score
)

# XGBoost
from xgboost import XGBRegressor

# TensorFlow/Keras
from tensorflow import keras
from tensorflow.keras import layers, models

house_df = pd.read_csv('Housing_Dataset_Regression.csv', index_col=0)
print(house_df.head())

# Check which columns have null values
house_df.info()

print(house_df['ocean_proximity'].unique())

"""### Data Pre-processing

#### Data Cleaning
"""

train = house_df.iloc[:810]
test = house_df.iloc[810:]

num_cols = train.select_dtypes(include=['number']).columns
cat_cols = train.select_dtypes(include=['object', 'category']).columns

train.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)

### **1. Fill Missing Values in Numerical Columns (Using Median of X_train)**
num_imputer = SimpleImputer(strategy='median')

# Fit on X_train and transform both X_train & test
train[num_cols] = num_imputer.fit_transform(train[num_cols])
test[num_cols] = num_imputer.transform(test[num_cols])

### **2. Fill Missing Values in Categorical Columns (Using Most Frequent Category of X_train)**
cat_imputer = SimpleImputer(strategy='most_frequent')

# Fit on X_train and transform both X_train & X_test
train[cat_cols] = cat_imputer.fit_transform(train[cat_cols])
test[cat_cols] = cat_imputer.transform(test[cat_cols])

print(train.head())
print(test.head())

print(train.shape)
print(test.shape)

Y_train = train['median_house_value']
X_train = train.drop('median_house_value', axis=1)

Y_test = test['median_house_value']
X_test = test.drop('median_house_value', axis=1)

print(X_train.head())
print(Y_train.head())
print(X_test.head())
print(Y_test.head())

print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

cleaned_df = pd.concat([train, test], ignore_index=True)
cleaned_df.drop('ocean_proximity', axis=1, inplace=True)

fig, axs = plt.subplots(9,1,dpi=95, figsize=(7,17))
i = 0
for col in cleaned_df.columns: # 10 columns in the df
    axs[i].boxplot(cleaned_df[col], vert=False)
    axs[i].set_ylabel(col)
    i+=1
    if i >= len(axs):
        break
plt.show()

"""#### Feature Engineering"""

# feature extraction - add/extract more features from the original df
X_train_extra = X_train.copy()

# Room density - indicate how spacious each household is
X_train_extra['room_density'] = X_train_extra['total_rooms'] / X_train_extra['households']

# Bedroom density - how many bedrooms each household has (on average)
X_train_extra['bedroom_density'] = X_train_extra['total_bedrooms'] / X_train_extra['households']

# Pop density - how crowded a household is
X_train_extra['pop_density'] = X_train_extra['population'] / X_train_extra['households']

# Income_bedroom - wealthier households tend to have more bedrooms (?)
X_train_extra['income_bedroom'] = X_train_extra['median_income'] * X_train_extra['total_bedrooms']


# Desining the same features but for X_test_extra dataset
X_test_extra = X_train.copy()
X_test_extra['room_density'] = X_test_extra['total_rooms'] / X_test_extra['households']
X_test_extra['bedroom_density'] = X_test_extra['total_bedrooms'] / X_test_extra['households']
X_test_extra['pop_density'] = X_test_extra['population'] / X_test_extra['households']
X_test_extra['income_bedroom'] = X_test_extra['median_income'] * X_test_extra['total_bedrooms']

print(X_train_extra.columns)
print(X_train_extra.head())

print(X_test_extra.columns)
print(X_test_extra.head())

"""#### Dimensionality Reduction"""

# Correlation Matrix - to visualise highly correlated columns

corr_matrix = house_df.drop(columns = ['ocean_proximity']).corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.show()

# Randomly remove columns from highly correlated column groups

# Compute the correlation matrix
house_df_reduced = house_df.drop(columns=['ocean_proximity'])
corr_matrix = house_df_reduced.corr().abs()  # Take absolute values to consider both positive & negative correlations

# Set the threshold for high correlation (e.g., 0.85)
threshold = 0.85

# Find pairs of highly correlated columns
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
high_corr_pairs = [(col, idx) for col in upper_tri.columns for idx in upper_tri.index if upper_tri.loc[idx, col] > threshold]

# Track columns to drop
columns_to_drop = set()

# Create a set of all columns in the original dataset
remaining_columns = set(house_df_reduced.columns)

# Iterate over all high correlation pairs and drop one column from each pair
for col1, col2 in high_corr_pairs:
    if col1 in remaining_columns and col2 in remaining_columns:
        # Randomly drop one column from the pair
        column_to_drop = np.random.choice([col1, col2])
        columns_to_drop.add(column_to_drop)
        remaining_columns.remove(column_to_drop)

# Drop the selected columns
house_df_reduced = house_df_reduced.drop(columns=columns_to_drop)

print(f"Dropped columns: {columns_to_drop}")
print("Dimensionality reduction complete!")

print(house_df_reduced.head())

# Correlation Matrix - to visualise highly correlated columns

corr_matrix = house_df_reduced.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.show()

# Separating features (X) and the target (Y)
house_df_reduced['ocean_proximity'] = house_df['ocean_proximity']
train_small = house_df_reduced.iloc[:860]
test_small = house_df_reduced.iloc[860:]

train_small.drop_duplicates(inplace=True)
test_small.drop_duplicates(inplace=True)


X_train_small = train_small.drop('median_house_value', axis=1)
X_test_small = test_small.drop('median_house_value', axis=1)

print(X_train_small.head())
print(X_test_small.head())

print(X_train_small.shape)
print(X_test_small.shape)

"""#### Feature Standardisation"""

def feature_standard(df_train, df_test):
    # Identify numerical and categorical columns
    num_cols = df_train.select_dtypes(include=['int64', 'float64']).columns

    # Step 2: Standardize only numerical columns
    scaler = StandardScaler()
    df_train[num_cols] = scaler.fit_transform(df_train[num_cols])  # Fit & transform on train set
    df_test[num_cols] = scaler.transform(df_test[num_cols])  # Transform only on test set

    return df_train, df_test

X_train_stand, X_test_stand = feature_standard(X_train, X_test)

print(X_train.head())
print(X_test.head())

# Standardising the "extra" features
X_train_extra_stand, X_test_extra_stand = feature_standard(X_train_extra, X_test_extra)

print(X_train_extra_stand.head())
print(X_test_extra_stand.head())

# Standardising the "small" features
X_train_small_stand, X_test_small_stand = feature_standard(X_train_small, X_test_small)

print(X_train_small_stand.head())
print(X_test_small_stand.head())

"""#### Standardising the Target Variable"""

# Initialize the scaler
y_scaler = StandardScaler()

# Fit on Y_train and transform both Y_train & Y_test
Y_train_stand = y_scaler.fit_transform(Y_train.values.reshape(-1, 1)).ravel()
Y_test_stand = y_scaler.transform(Y_test.values.reshape(-1, 1)).ravel()

print("Y_train_small and Y_test_small have been standardised!")
print(Y_train_stand[:5])
print(Y_test_stand[:5])

"""#### Ordinal Encoding"""

# Ordinal Encoding of the 'ocean_proximity' column

def oridnal_encoding(df_train, df_test):
    # Identifycategorical columns
    cat_cols = df_train.select_dtypes(include=['object', 'category']).columns

    # Step 1: Apply Ordinal Encoding to categorical columns
    encoder = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)  # Assign -1 for unknown categories
    df_train_encoded = df_train.copy()
    df_test_encoded = df_test.copy()

    df_train_encoded[cat_cols] = encoder.fit_transform(df_train[cat_cols])  # Fit & transform on train set
    df_test_encoded[cat_cols] = encoder.transform(df_test[cat_cols])  # Transform only on test set

    return df_train_encoded, df_test_encoded

X_train, X_test = oridnal_encoding(X_train, X_test)

print(X_train.head())
print(X_test.head())
print(X_train['ocean_proximity'].unique())
print(X_test['ocean_proximity'].unique())

# Ordinal Encoding of the "extra" dataset

X_train_extra, X_test_extra = oridnal_encoding(X_train_extra, X_test_extra)

print(X_train_extra.head())
print(X_test_extra.head())

# Ordinal encoding for the "small" dataset

X_train_small, X_test_small = oridnal_encoding(X_train_small, X_test_small)

print(X_train_small.head())
print(X_test_small.head())

# Ordinal Encoding for all _stand datasets

X_train_stand, X_test_stand = oridnal_encoding(X_train_stand, X_test_stand)

x_train_extra_stand, X_test_extra_stand = oridnal_encoding(X_train_extra_stand, X_test_extra_stand)

X_train_small_stand, X_test_small_stand = oridnal_encoding(X_train_small_stand, X_test_small_stand)

# print(X_train_stand.head())
# print(X_test_stand.head())

"""### Basic Models
I.e., with default parameters

#### Lasso Regressor
"""

# The most basic Lasso Regressor Model

# Initialize the Lasso model
lasso_regressor = Lasso(alpha=0.1)  # alpha is the regularization parameter

# Train the model
lasso_regressor.fit(X_train, Y_train)

# Make predictions
y_pred = lasso_regressor.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)
evs = explained_variance_score(Y_test, y_pred)
mape = np.mean(np.abs((Y_test - y_pred) / Y_test)) * 100

# Print the results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"Explained Variance Score (EVS): {evs:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.4f}%")

"""#### Random Forest"""

# Initialize the model
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_regressor.fit(X_train, Y_train)

# Make predictions
y_pred = rf_regressor.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)
evs = explained_variance_score(Y_test, y_pred)
mape = np.mean(np.abs((Y_test - y_pred) / Y_test)) * 100

# Print the results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"Explained Variance Score (EVS): {evs:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.4f}%")

"""#### XGBoost"""

# Initialize XGBoost Regressor with default parameters
xgb_regressor = XGBRegressor(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)

# Train the model
xgb_regressor.fit(X_train, Y_train)

# Make predictions
Y_pred_xgb = xgb_regressor.predict(X_test)

# Compute evaluation metrics
mae = mean_absolute_error(Y_test, Y_pred_xgb)
mse = mean_squared_error(Y_test, Y_pred_xgb)
rmse = mse ** 0.5
r2 = r2_score(Y_test, Y_pred_xgb)

# Print results
print(f"XGBoost - MAE: {mae:.4f}")
print(f"XGBoost - MSE: {mse:.4f}")
print(f"XGBoost - RMSE: {rmse:.4f}")
print(f"XGBoost - R² Score: {r2:.4f}")

"""### Fine-tuning the models: Standardised Features

#### Lasso Regressor
"""

# Lasso Regressor with standardisation

# Initialize the Lasso model
lasso_regressor = Lasso(alpha=0.1)  # alpha is the regularization parameter

# Train the model
lasso_regressor.fit(X_train_stand, Y_train_stand)

# Make predictions
y_pred = lasso_regressor.predict(X_test_stand)

# Calculate evaluation metrics
mae = mean_absolute_error(Y_test_stand, y_pred)
mse = mean_squared_error(Y_test_stand, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test_stand, y_pred)
evs = explained_variance_score(Y_test_stand, y_pred)
mape = np.mean(np.abs((Y_test_stand - y_pred) / Y_test_stand)) * 100

# Print the results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"Explained Variance Score (EVS): {evs:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.4f}%")

"""#### Random Forest"""

# Initialize the model
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
rf_regressor.fit(X_train_stand, Y_train_stand)

# Make predictions
y_pred = rf_regressor.predict(X_test_stand)

# Calculate evaluation metrics
mae = mean_absolute_error(Y_test_stand, y_pred)
mse = mean_squared_error(Y_test_stand, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test_stand, y_pred)
evs = explained_variance_score(Y_test_stand, y_pred)
mape = np.mean(np.abs((Y_test_stand - y_pred) / Y_test_stand)) * 100

# Print the results
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"Explained Variance Score (EVS): {evs:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.4f}%")

"""#### XGBoost"""

# Initialize XGBoost Regressor with default parameters
xgb_regressor = XGBRegressor(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)

# Train the model
xgb_regressor.fit(X_train_stand, Y_train_stand)

# Make predictions
Y_pred_xgb = xgb_regressor.predict(X_test_stand)

# Compute evaluation metrics
mae = mean_absolute_error(Y_test_stand, Y_pred_xgb)
mse = mean_squared_error(Y_test_stand, Y_pred_xgb)
rmse = mse ** 0.5
r2 = r2_score(Y_test_stand, Y_pred_xgb)

# Print results
print(f"XGBoost - MAE: {mae:.4f}")
print(f"XGBoost - MSE: {mse:.4f}")
print(f"XGBoost - RMSE: {rmse:.4f}")
print(f"XGBoost - R² Score: {r2:.4f}")

"""### Fine-tuning the models: Parameter Optimisation

#### Lasso Regressor
"""

# Initialize Lasso model
lasso = Lasso()

# Define the distribution for alpha to sample from
# Try a narrower range for alpha to focus more on the regions near the optimal value
param_dist = {
    'alpha': np.logspace(-4, 1, 6)  # Adjusted range for alpha
}

# Initialize RandomizedSearchCV with cross-validation
random_search = RandomizedSearchCV(estimator=lasso, param_distributions=param_dist, n_iter=10, cv=5,
                                   n_jobs=-1, scoring='neg_mean_squared_error', random_state=42)

# Fit the model
random_search.fit(X_train, Y_train)

# Get the best parameters and model
best_lasso_model = random_search.best_estimator_

# Make predictions using the best model
y_pred = best_lasso_model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(Y_test, y_pred)
evs = explained_variance_score(Y_test, y_pred)
mape = np.mean(np.abs((Y_test - y_pred) / Y_test)) * 100

# Print the best alpha and evaluation results
print(f"Best Alpha: {random_search.best_params_['alpha']}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"Explained Variance Score (EVS): {evs:.4f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.4f}%")

"""#### Random Forest"""

# Define a more conservative parameter grid
param_dist = {
    'n_estimators': [100, 200, 300],  # Number of trees
    'max_depth': [None, 10, 20, 30],  # Max depth
    'min_samples_split': [2, 5, 10],  # Min samples to split a node
    'min_samples_leaf': [1, 2, 4],  # Min samples at a leaf node
    'max_features': ['sqrt', 'log2', None],  # Features to consider for each split
    'bootstrap': [True, False]  # Whether to use bootstrap samples
}

# Initialize RandomForestRegressor with a random seed for reproducibility
rf = RandomForestRegressor(random_state=42)

# RandomizedSearchCV with cross-validation to tune hyperparameters
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_dist,
                                   n_iter=50, cv=5, verbose=2, random_state=42, n_jobs=-1)

# Fit the model
random_search.fit(X_train, Y_train)

# Get the best hyperparameters
best_params = random_search.best_params_
print("Best Hyperparameters: ", best_params)

# Evaluate the optimized model
best_rf_model = random_search.best_estimator_
Y_pred = best_rf_model.predict(X_test)

# Evaluate model performance
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
rmse = mse ** 0.5
r2 = r2_score(Y_test, Y_pred)

# Print evaluation metrics
print(f"Optimized Random Forest - MAE: {mae:.4f}")
print(f"Optimized Random Forest - MSE: {mse:.4f}")
print(f"Optimized Random Forest - RMSE: {rmse:.4f}")
print(f"Optimized Random Forest - R² Score: {r2:.4f}")

"""#### XGBoost"""

!pip install optuna

# Same as above but with cross-validation

# Define the objective function to minimize
def objective(trial):
    # Define the hyperparameter search space
    param = {
        'max_depth': trial.suggest_int('max_depth', 3, 15),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10)
    }

    # Initialize XGBoost Regressor with suggested hyperparameters
    model = XGBRegressor(**param, objective="reg:squarederror", random_state=42)

    # Use cross-validation to evaluate the model (5-fold cross-validation)
    # 'neg_mean_absolute_error' is used to return negative values (to minimize)
    cv_scores = cross_val_score(model, X_train, Y_train, cv=5, scoring='neg_mean_absolute_error')

    # Return the mean of the negative MAE scores
    mean_mae = np.mean(cv_scores)  # This will be negative, so we return the positive value
    return -mean_mae  # Optuna minimizes the objective function, so we return negative MAE

# Create a study object to optimize the hyperparameters
study = optuna.create_study(direction='minimize')

# Perform optimization
study.optimize(objective, n_trials=200)  # Number of trials you want to run

# Print the best hyperparameters and the best score
print("Best Hyperparameters: ", study.best_params)
print("Best MAE: ", study.best_value)

# Train the final model with the best hyperparameters
best_model = XGBRegressor(**study.best_params, objective="reg:squarederror", random_state=42)
best_model.fit(X_train, Y_train)

# Predict and evaluate the final model
Y_pred_best = best_model.predict(X_test)
mae = mean_absolute_error(Y_test, Y_pred_best)
mse = mean_squared_error(Y_test, Y_pred_best)
rmse = mse ** 0.5
r2 = r2_score(Y_test, Y_pred_best)

# Print final evaluation metrics
print(f"Fine-Tuned XGBoost - MAE: {mae:.4f}")
print(f"Fine-Tuned XGBoost - MSE: {mse:.4f}")
print(f"Fine-Tuned XGBoost - RMSE: {rmse:.4f}")
print(f"Fine-Tuned XGBoost - R² Score: {r2:.4f}")

"""## Task 2. Classification"""

titanic = pd.read_csv('Titanic_Dataset_Classification.csv', index_col=0)
print(titanic.head())

# Check which columns have null values
titanic.info()
print(len(titanic))

print(titanic['Sex'].unique())
print(titanic['Embarked'].unique())
print(titanic['Pclass'].unique())

print(titanic.isnull().sum())
print(titanic.shape)
print(f'{round(175 / 890 * 100, 2)}% of the Age column is missing')

print(titanic.duplicated().sum())

"""### Data Pre-processing"""

# Drop Name and Ticket column as they cannot be used by the ML algorithms and
# Do not provide any significant information

titanic.drop(['Name', 'Ticket No.'], axis=1, inplace=True)

train = titanic.iloc[:750]
test = titanic.iloc[750:]

train.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)

print(train.head())
print(test.head())

print(train.shape)
print(test.shape)

sur_imputer = SimpleImputer(strategy='most_frequent')

# Impute missing values in 'Survival' column
train['Survival'] = sur_imputer.fit_transform(train[['Survival']])
test['Survival'] = sur_imputer.transform(test[['Survival']])

print(train.isnull().sum())
print(test.isnull().sum())

train['Survival'] = train['Survival'].astype('object')
test['Survival'] = test['Survival'].astype('object')

print(train.info())
print(test.info())

"""#### Data Cleaning"""

num_cols = train.select_dtypes(include=['number']).columns
cat_cols = train.select_dtypes(include=['object', 'category']).columns

num_imputer = SimpleImputer(strategy='median')

train[num_cols] = num_imputer.fit_transform(train[num_cols])
test[num_cols] = num_imputer.transform(test[num_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')

train[cat_cols] = cat_imputer.fit_transform(train[cat_cols])
test[cat_cols] = cat_imputer.transform(test[cat_cols])

# Print confirmation
print("Missing values filled successfully!")
print(f'X_train:\n{train.isnull().sum()}\n')
print(f'X_test:\n{test.isnull().sum()}\n')

Y_train = train['Survival']
X_train = train.drop('Survival', axis=1)

Y_test = test['Survival']
X_test = test.drop('Survival', axis=1)

# print(X_train.head())
print(Y_train.head())
# print(X_test.head())
print(Y_test.head())

# print(X_train.shape)
print(Y_train.shape)
# print(X_test.shape)
print(Y_test.shape)

print(X_train.isnull().sum())
print(X_test.isnull().sum())
print(Y_train.isnull().sum())
print(Y_test.isnull().sum())

print('\nDuplicates:')
print(X_train.duplicated().sum())
print(X_test.duplicated().sum())

"""#### Label Encoding"""

X_train.info()
Y_train.info()
# To encode?

# List of columns to encode
col_to_encode = ['Sex', 'Embarked']

# Initialize One-Hot Encoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')  # Ignore unknown categories in X_test

# Fit on X_train and Transform Both X_train and X_test
X_train_encoded = ohe.fit_transform(X_train[col_to_encode])
X_test_encoded = ohe.transform(X_test[col_to_encode])

# Convert to DataFrame
# Use `col_to_encode` to generate proper feature names for the encoded columns
X_train_encoded = pd.DataFrame(X_train_encoded, columns=ohe.get_feature_names_out(col_to_encode))
X_test_encoded = pd.DataFrame(X_test_encoded, columns=ohe.get_feature_names_out(col_to_encode))

X_train.drop(col_to_encode, axis=1, inplace=True)
X_test.drop(col_to_encode, axis=1, inplace=True)

X_train = pd.concat([X_train, X_train_encoded], axis=1)
X_test = pd.concat([X_test, X_test_encoded], axis=1)


# Output the encoded data
# print("Encoded X_train:")
# print(X_train.head())
# print("\nEncoded X_test:")
# print(X_test.head())
# print(X_train.info())

print(Y_train.info())
print(Y_test.info())

"""#### Feature Standardisation"""

# List of numerical columns to standardize
continuous_cols = ['Age', 'Fare', 'SibSp', 'Parch']

# Initialize StandardScaler
scaler = MinMaxScaler()

# Standardize the numerical columns
X_train_continuous = scaler.fit_transform(X_train[continuous_cols])
X_test_continuous = scaler.transform(X_test[continuous_cols])
joblib.dump(scaler, 'minmax_scaler.pkl')

# Convert the scaled continuous features back to DataFrame
X_train_continuous_df = pd.DataFrame(X_train_continuous, columns=continuous_cols)
X_test_continuous_df = pd.DataFrame(X_test_continuous, columns=continuous_cols)

# Drop the original numerical columns from X_train and X_test
X_train.drop(continuous_cols, axis=1, inplace=True)
X_test.drop(continuous_cols, axis=1, inplace=True)

# Combine the standardized continuous features with the encoded categorical features
X_train_final = pd.concat([X_train, X_train_continuous_df], axis=1)
X_test_final = pd.concat([X_test, X_test_continuous_df], axis=1)

# Output the final data
# print("Final X_train:")
# print(X_train_final.head())
# print("\nFinal X_test:")
# print(X_test_final.head())
print(X_train_final.info())


# For when I might need the scaler again
# # Load the scaler
# scaler = joblib.load('minmax_scaler.pkl')

# # Use the loaded scaler to transform new data
# X_new_scaled = scaler.transform(X_new[['sibsp', 'parch']])

Y_train = pd.to_numeric(Y_train, errors="coerce")
Y_test = pd.to_numeric(Y_test, errors="coerce")

print(X_train_final.info())
print(X_test_final.info())
print(Y_train.info())
print(Y_test.info())

print(X_train_final.shape)
print(X_test_final.shape)
print(Y_train.shape)
print(Y_test.shape)

"""### Basic Models

#### KNN
"""

# Initialize the KNN model
knn = KNeighborsClassifier(n_neighbors=5)  # You can tune the number of neighbors

# Train the model
knn.fit(X_train_final, Y_train)

# Make predictions on the test set
Y_pred_final = knn.predict(X_test_final)

# Evaluate the model with different metrics
accuracy = accuracy_score(Y_test, Y_pred_final)
f1 = f1_score(Y_test, Y_pred_final)
precision = precision_score(Y_test, Y_pred_final)
recall = recall_score(Y_test, Y_pred_final)
roc_auc = roc_auc_score(Y_test, Y_pred_final)

# Print the evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"F1-Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"ROC AUC: {roc_auc}")

"""#### SVM"""

# Initialize the SVM model
svm = SVC(kernel='linear')  # You can try different kernels like 'rbf', 'poly', etc.

# Train the model
svm.fit(X_train_final, Y_train)

# Make predictions on the test set
Y_pred_svm = svm.predict(X_test_final)

# Evaluate the model with different metrics
accuracy = accuracy_score(Y_test, Y_pred_svm)
f1 = f1_score(Y_test, Y_pred_svm)
precision = precision_score(Y_test, Y_pred_svm)
recall = recall_score(Y_test, Y_pred_svm)
roc_auc = roc_auc_score(Y_test, Y_pred_svm)

# Print the evaluation metrics
print(f"Accuracy: {accuracy}")
print(f"F1-Score: {f1}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"ROC AUC: {roc_auc}")

"""#### Neural Networks"""

# Define the neural network model
model = keras.Sequential([
    layers.Dense(16, activation='relu', input_shape=(X_train_final.shape[1],)),  # Hidden layer with 16 neurons
    layers.Dense(8, activation='relu'),  # Another hidden layer with 8 neurons
    layers.Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_final, Y_train, epochs=50, batch_size=32, validation_data=(X_test_final, Y_test))

# Evaluate the model
eval_results = model.evaluate(X_test_final, Y_test)
print(f'Loss: {eval_results[0]:.4f}, Accuracy: {eval_results[1]:.4f}')

# Make predictions on the test set
Y_pred = model.predict(X_test_final)

# Convert predictions to binary values (0 or 1)
Y_pred_binary = (Y_pred > 0.5).astype(int)

# Compute additional evaluation metrics
f1 = f1_score(Y_test, Y_pred_binary)
precision = precision_score(Y_test, Y_pred_binary)
recall = recall_score(Y_test, Y_pred_binary)
roc_auc = roc_auc_score(Y_test, Y_pred_binary)

# Print additional metrics
print(f'F1-Score: {f1:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'ROC AUC: {roc_auc:.4f}')

"""### Model Optimisation

#### KNN
"""

# Objective function for Optuna with 5-fold cross-validation
def objective(trial):
    # Define the hyperparameters to optimize
    n_neighbors = trial.suggest_int('n_neighbors', 1, 20)  # K value between 1 and 20
    weights = trial.suggest_categorical('weights', ['uniform', 'distance'])  # Weighting strategy
    metric = trial.suggest_categorical('metric', ['euclidean', 'manhattan', 'chebyshev'])  # Distance metric
    algorithm = trial.suggest_categorical('algorithm', ['auto', 'ball_tree', 'kd_tree', 'brute'])  # Algorithm type

    # Initialize the KNN model
    model = KNeighborsClassifier(
        n_neighbors=n_neighbors,
        weights=weights,
        metric=metric,
        algorithm=algorithm
    )

    # Perform 5-fold cross-validation
    f1_scores = cross_val_score(model, X_train_final, Y_train, cv=5, scoring='f1')

    # Return the mean F1-score
    return f1_scores.mean()

# Create the Optuna study and optimize
study = optuna.create_study(direction='maximize')  # Maximizing the F1-score
study.optimize(objective, n_trials=100)  # Run 100 trials

# Print the best hyperparameters and evaluation metrics
print("Best Hyperparameters:", study.best_params)
print("Best F1-Score:", study.best_value)

# Train the best model on the entire training set
best_knn = KNeighborsClassifier(**study.best_params)
best_knn.fit(X_train_final, Y_train)

# Evaluate the best model on the test set
Y_pred_best_knn = best_knn.predict(X_test_final)

# Print the evaluation metrics for the best model
print(f"Accuracy: {accuracy_score(Y_test, Y_pred_best_knn)}")
print(f"F1-Score: {f1_score(Y_test, Y_pred_best_knn)}")
print(f"Precision: {precision_score(Y_test, Y_pred_best_knn)}")
print(f"Recall: {recall_score(Y_test, Y_pred_best_knn)}")
print(f"ROC AUC: {roc_auc_score(Y_test, Y_pred_best_knn)}")

"""#### SVM"""

# Objective function for Optuna to fine-tune SVM
def objective(trial):
    # Define the hyperparameters to optimize
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)  # Regularization parameter
    kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])  # Kernel type
    gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])  # Kernel coefficient for rbf/poly kernels
    degree = trial.suggest_int('degree', 1, 5) if kernel == 'poly' else 3  # Degree for poly kernel
    class_weight = trial.suggest_categorical('class_weight', [None, 'balanced'])  # Class weight

    # Initialize the SVM model with the selected hyperparameters
    model = SVC(C=C, kernel=kernel, gamma=gamma, degree=degree, class_weight=class_weight)

    # Perform cross-validation to evaluate the model
    score = cross_val_score(model, X_train_final, Y_train, cv=3, scoring='accuracy').mean()

    # Return the score (we are maximizing the accuracy)
    return score

# Create the Optuna study and optimize
study = optuna.create_study(direction='maximize')  # We are maximizing the accuracy score
study.optimize(objective, n_trials=100, timeout = 60)  # Run 100 trials

# Print the best hyperparameters and evaluation metrics
print("Best Hyperparameters:", study.best_params)
print("Best Accuracy:", study.best_value)

# Get the best model based on the study's best hyperparameters
best_svm = SVC(**study.best_params)
best_svm.fit(X_train_final, Y_train)

# Evaluate the best model on the test set
Y_pred_best_svm = best_svm.predict(X_test_final)

# Print the evaluation metrics for the best model
print(f"Accuracy: {accuracy_score(Y_test, Y_pred_best_svm)}")
print(f"F1-Score: {f1_score(Y_test, Y_pred_best_svm)}")
print(f"Precision: {precision_score(Y_test, Y_pred_best_svm)}")
print(f"Recall: {recall_score(Y_test, Y_pred_best_svm)}")
print(f"ROC AUC: {roc_auc_score(Y_test, Y_pred_best_svm)}")

"""#### Neural Networks"""

# Define the Optuna objective function to optimize the neural network
def objective(trial):
    # Define the model
    model = models.Sequential()

    # Hyperparameters to optimize
    num_layers = trial.suggest_int('num_layers', 1, 3)  # Number of layers
    for i in range(num_layers):
        num_neurons = trial.suggest_int(f'n_neurons_l{i+1}', 32, 128, log=True)  # Neurons per layer
        model.add(layers.Dense(num_neurons, activation='relu'))  # Hidden layers

    # Add output layer
    model.add(layers.Dense(1, activation='sigmoid'))  # Binary output for classification

    # Compile the model
    model.compile(
        optimizer=tf.keras.optimizers.Adam(
            learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1, log=True)
        ),
        loss='binary_crossentropy',  # Use binary crossentropy for binary classification
        metrics=['accuracy']
    )

    # Train the model
    model.fit(X_train_final, Y_train, epochs=10, batch_size=trial.suggest_int('batch_size', 16, 64), verbose=0)

    # Make predictions on the test set
    Y_pred_proba = model.predict(X_test_final)  # Predicted probabilities
    Y_pred = (Y_pred_proba > 0.5).astype('int32')  # Convert probabilities to binary class predictions

    # Evaluate the model using different metrics
    accuracy = accuracy_score(Y_test, Y_pred)
    f1 = f1_score(Y_test, Y_pred)
    precision = precision_score(Y_test, Y_pred)
    recall = recall_score(Y_test, Y_pred)
    roc_auc = roc_auc_score(Y_test, Y_pred_proba)

    # Print evaluation metrics
    print(f"Accuracy: {accuracy:.4f}")
    print(f"F1-Score: {f1:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"ROC AUC: {roc_auc:.4f}")

    return accuracy  # Optuna will maximize this value

# Create Optuna study
study = optuna.create_study(direction='maximize')  # We are maximizing accuracy
study.optimize(objective, n_trials=50)  # Run optimization for 50 trials

# Get the best hyperparameters
best_params = study.best_params
print(f"Best Hyperparameters: {best_params}")
print(f"Best Accuracy: {study.best_value}")